package pages;

import java.util.List;

import com.framework.device.TestContext;
import com.framework.events.IClient;
import com.framework.pages.BasePage;

import events.IXPNEvents;

public class FAVOURITE_EDIT_PAGE extends BasePage {

	public FAVOURITE_EDIT_PAGE(TestContext testContext) {
		super(testContext);
		createValidationList();

		validatePage(validateElementList);

	}

	public void doValidation() {
		createValidationList();

		validatePage(validateElementList);
	}

	public FAVOURITE_EDIT_PAGE(TestContext testContext, List<String> extraElementList) {
		super(testContext);
		createValidationList();

		validateElementList.addAll(extraElementList);

		validatePage(validateElementList);
	}

	private void createValidationList() {

		DummyPage dummyPage = new DummyPage(testContext);

		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_BACK_BUTTON);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_BUY_CLOTHES);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_BUY_CLOTHES_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_BUY_A_MOBILE_PHONE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_BUY_A_MOBILE_PHONE_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_BUY_ELECTRONICS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_BUY_ELECTRONICS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_SHOPPING_DEALS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_SHOPPING_DEALS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_SEND_CAKES_OR_FLOWERS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_SHOPPING_SEND_CAKES_OR_FLOWERS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_MOBILE_TOP_UP);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_MOBILE_TOP_UP_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_BEST_DATA_PLANS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_BEST_DATA_PLANS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_PAY_PHONE_BILL);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RECHARGE_PAY_PHONE_BILL_CHECKBOX);
		dummyPage.swipe(100, 700, 100, 50, 2000);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_CUISINE_OR_DISH_SEARCH);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_CUISINE_OR_DISH_SEARCH_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_RESTAURANT_SEARCH);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_RESTAURANT_SEARCH_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_MEAL_DISCOUNTS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_MEAL_DISCOUNTS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_RESERVE_A_TABLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_RESERVE_A_TABLE_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_ORDER_A_PIZZA);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_FOOD_DELIVERY_ORDER_A_PIZZA_CHECKBOX);

		dummyPage.swipe(100, 700, 100, 50, 2000);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FINDE_ME_THE_BEST_FLIGHT);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FINDE_ME_THE_BEST_FLIGHT_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FLIGHT_WEB_CHECK_IN);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FLIGHT_WEB_CHECK_IN_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FIND_ME_A_HOTEL);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FIND_ME_A_HOTEL_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_TRAIN_PNR_STATUS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_TRAIN_PNR_STATUS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FIND_ME_A_TRAIN);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_FIND_ME_A_TRAIN_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_BOOK_ME_A_BUS_TICKET);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_TRAVEL_BOOK_ME_A_BUS_TICKET_CHECKBOX);
		dummyPage.swipe(100, 700, 100, 50, 2000);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_TITLE);
		// verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_ELECTRICIAN);
		// verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_ELECTRICIAN_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_APPLIANCE_REPAIR);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_APPLIANCE_REPAIR_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_HOME_REPAIRS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_HOME_REPAIRS_CHECKBOX);
		/*
		 * verifyElementFound(IXPNEvents.
		 * FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_PICK_UP_AND_DROP_TODAY
		 * ); verifyElementFound(IXPNEvents.
		 * FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_PICK_UP_AND_DROP_TODAY_CHECKBOX
		 * ); //verifyElementFound(IXPNEvents.
		 * FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_SCHEDULE_A_COURIER);
		 * //verifyElementFound(IXPNEvents.
		 * FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_SCHEDULE_A_COURIER_CHECKBOX
		 * ); //verifyElementFound(IXPNEvents.
		 * FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_CUSTOMER_CARE_INFO);
		 * //verifyElementFound(IXPNEvents.
		 * FAVOURITE_EDIT_FAVOURITE_TASKS_UTILITIES_REPAIRS_CUSTOMER_CARE_INFO_CHECKBOX
		 * );
		 */
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_ATM);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_ATM_CHECKBOX);

		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_CAFE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_CAFE_CHECKBOX);
		dummyPage.swipe(100, 700, 100, 200, 2000);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_BUS_STOP);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_BUS_STOP_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_TRAIN_STATION);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_TRAIN_STATION_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_HOSPITAL);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_NEARBY_HOSPITAL_CHECKBOX);

		dummyPage.swipe(100, 700, 100, 50, 2000);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_GIVE_ME_SHOW_TIMINGS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_GIVE_ME_SHOW_TIMINGS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_MOVIE_REVIEWS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_MOVIE_REVIEWS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_BOOK_TICKETS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_MOVIES_BOOK_TICKETS_CHECKBOX);
		dummyPage.swipe(100, 700, 100, 50, 2000);

		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_WAKE_UP_CALL);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_WAKE_UP_CALL_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_BIRTHDAY_REMINDER);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_BIRTHDAY_REMINDER_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_MEETING_REMINDER);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_MEETING_REMINDER_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_MEDICINE_REMINDER);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_MEDICINE_REMINDER_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_REMINDER_TO_DRINK_WATER);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_REMINDER_TO_DRINK_WATER_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_REMINDER_TO_CALL);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_REMINDER_TO_CALL_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_REMINDER_TO_PAY_BILS);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_REMINDERS_REMINDER_TO_PAY_BILS_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RESTAURANTS_TITLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RESTAURANTS_RESERVE_A_TABLE);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RESTAURANTS_RESERVE_A_TABLE_CHECKBOX);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RESTAURANTS_RECOMMEND_A_RESTAURANT);
		verifyElementFound(IXPNEvents.FAVOURITE_EDIT_FAVOURITE_TASKS_RESTAURANTS_RECOMMEND_A_RESTAURANT_CHECKBOX);
		dummyPage.swipe("down", 700, 5000);

	}
}

/*
 * public HomePage clickCancel() { clickElement(IXPNEvents.LOGOUTPAGE_Cancel);
 * return new HomePage(this.getTestContext());
 * 
 * }
 */
